#!/bin/bash
##SBATCH -A see180004p # 2021 Allocation -- This might change in the following years.
#SBATCH -J particle-pthreads16
#SBATCH -o particle-pthreads16.stdout
#SBATCH -n 16         
#SBATCH -p RM
#SBATCH -t 00:10:00     
#SBATCH -N 1         
./pthreads -p 16 -n 1000 -o pthreads.txt
